root: true

env:
  browser: true
  es2021: true

extends:
  - airbnb-base
  - 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  'linebreak-style': 0
  'max-len': ['error', { 'code': 200 }]

  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest
